version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iwel-iwel-dev-app:latest
    container_name: iwel_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - iwel-network

  web:
    image: nginx:stable-alpine
    container_name: iwel_web
    restart: unless-stopped
    ports:
      - "9900:80"
    volumes:
      - .:/var/www/html
      # Mount the entire nginx configuration directory to avoid file vs directory mount issues
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - iwel-network

  db:
    image: mysql:8.0
    container_name: iwel_db
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - iwel-network

volumes:
  dbdata:
    driver: local

networks:
  iwel-network:
    driver: bridge
